--
-- PostgreSQL database dump
--

\restrict VrBcl8f5fuavBOMJfHOkRRBiL90M2GhbT873q7jprFVIMs1GHuCczYIBPob4yrK

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    bio text NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO aistudyhub_user;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_assistant_aiconversation; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.ai_assistant_aiconversation (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.ai_assistant_aiconversation OWNER TO aistudyhub_user;

--
-- Name: ai_assistant_aiconversation_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.ai_assistant_aiconversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_assistant_aiconversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_assistant_aimessage; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.ai_assistant_aimessage (
    id bigint NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    conversation_id bigint NOT NULL
);


ALTER TABLE public.ai_assistant_aimessage OWNER TO aistudyhub_user;

--
-- Name: ai_assistant_aimessage_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.ai_assistant_aimessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_assistant_aimessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO aistudyhub_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO aistudyhub_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO aistudyhub_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO aistudyhub_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO aistudyhub_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO aistudyhub_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_activity; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.dashboard_activity (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.dashboard_activity OWNER TO aistudyhub_user;

--
-- Name: dashboard_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.dashboard_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO aistudyhub_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO aistudyhub_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO aistudyhub_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO aistudyhub_user;

--
-- Name: notes_category; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.notes_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_category OWNER TO aistudyhub_user;

--
-- Name: notes_category_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.notes_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes_note; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.notes_note (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_note OWNER TO aistudyhub_user;

--
-- Name: notes_note_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.notes_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes_note_tags; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.notes_note_tags (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.notes_note_tags OWNER TO aistudyhub_user;

--
-- Name: notes_note_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.notes_note_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_note_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes_tag; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.notes_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.notes_tag OWNER TO aistudyhub_user;

--
-- Name: notes_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.notes_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planner_task; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.planner_task (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    due_date date,
    priority character varying(10) NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.planner_task OWNER TO aistudyhub_user;

--
-- Name: planner_task_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.planner_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planner_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_resource; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.resources_resource (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    link character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    resource_type_id bigint
);


ALTER TABLE public.resources_resource OWNER TO aistudyhub_user;

--
-- Name: resources_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.resources_resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources_resourcetype; Type: TABLE; Schema: public; Owner: aistudyhub_user
--

CREATE TABLE public.resources_resourcetype (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.resources_resourcetype OWNER TO aistudyhub_user;

--
-- Name: resources_resourcetype_id_seq; Type: SEQUENCE; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE public.resources_resourcetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resourcetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.accounts_profile (id, bio, image, created_at, user_id) FROM stdin;
1		profiles/image.png	2026-08-10 16:34:42.171275+00	1
2		profiles/default.png	2026-08-11 10:29:30.720078+00	2
3		profiles/project.jpg	2026-08-11 10:36:06.702504+00	3
\.


--
-- Data for Name: ai_assistant_aiconversation; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.ai_assistant_aiconversation (id, title, created_at, user_id) FROM stdin;
1	"Explain the difference between a Python list and 	2026-08-10 17:47:06.659074+00	1
2	"Explain the difference between a Python list and 	2026-08-10 17:47:54.470786+00	1
3	"Explain the difference between a Python list and 	2026-08-11 09:57:53.048175+00	1
4	Explain Python decorators	2026-08-11 10:02:54.236754+00	1
5	Explain Python decorators	2026-08-11 10:02:56.970318+00	1
8	"Explain the difference between a Python list and 	2026-08-11 10:54:40.460751+00	1
9	"Explain the difference between a Python list and 	2026-08-11 11:01:33.710579+00	1
10	"Explain the difference between a Python list and 	2026-08-11 11:16:04.621696+00	1
11	"Explain the difference between a Python list and 	2026-08-11 11:29:07.512319+00	1
\.


--
-- Data for Name: ai_assistant_aimessage; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.ai_assistant_aimessage (id, role, content, created_at, conversation_id) FROM stdin;
1	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-10 17:47:06.661427+00	1
2	ASSISTANT	⚠️ Sorry, the AI service is unavailable right now. Please try again.	2026-08-10 17:47:07.070871+00	1
3	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-10 17:47:54.474688+00	2
4	ASSISTANT	⚠️ Sorry, the AI service is unavailable right now. Please try again.	2026-08-10 17:47:54.830491+00	2
5	USER	Explain Python decorators	2026-08-10 17:49:54.091972+00	2
6	ASSISTANT	⚠️ Sorry, the AI service is unavailable right now. Please try again.	2026-08-10 17:49:54.545602+00	2
7	USER	Explain Python decorators	2026-08-11 09:36:46.473758+00	2
8	ASSISTANT	⚠️ Sorry, the AI service is unavailable right now. Please try again.	2026-08-11 09:36:46.854968+00	2
9	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-11 09:57:53.050078+00	3
10	ASSISTANT	⚠️ Sorry, the AI service is unavailable right now. Please try again.	2026-08-11 09:57:53.420871+00	3
11	USER	Explain Python decorators	2026-08-11 10:02:54.238879+00	4
12	USER	Explain Python decorators	2026-08-11 10:02:56.972561+00	5
14	ASSISTANT	In Python, a **decorator** is a tool that allows you to modify or extend the behavior of a function or class **without permanently changing its code**. \n\nThink of a decorator like **gift wrapping**:\n* The **present** inside is your original function.\n* The **wrapping paper** is the decorator.\n* The present stays the same, but the wrapping adds extra features (looks nice, conceals the inside) before you open it.\n\n---\n\n### The Secret Behind Decorators: First-Class Functions\n\nTo understand decorators, you must first know that in Python, **functions are objects**. This means you can:\n1. Assign functions to variables.\n2. Pass functions as arguments to other functions.\n3. Return functions from other functions.\n\nHere is a basic function passed as an argument:\n```python\ndef shout(text):\n    return text.upper()\n\n\ndef greet(func):\n    # 'func' is the shout function passed in\n    greeting = func("Hello")\n    print(greeting)\n\n\ngreet(shout)  # Output: HELLO\n```\n\n---\n\n### How a Decorator Works (Step-by-Step)\n\nA decorator is simply a function that takes another function as an input, wraps it with extra code, and returns the modified function.\n\n#### 1. The "Manual" Way\nHere is how you write a decorator without any special syntax:\n\n```python\n# 1. The Decorator Function\ndef my_decorator(func):\n    def wrapper():\n        print("--- Something is happening BEFORE the function is called. ---")\n        func()  # Execute the original function\n        print("--- Something is happening AFTER the function is called. ---")\n\n    return wrapper  # Return the new function containing the extra behavior\n\n\n# 2. The Original Function\ndef say_hello():\n    print("Hello!")\n\n\n# 3. Manually decorating the function\nsay_hello = my_decorator(say_hello)\n\n# 4. Calling the function\nsay_hello()\n```\n\n**Output:**\n```text\n--- Something is happening BEFORE the function is called. ---\nHello!\n--- Something is happening AFTER the function is called. ---\n```\n\n#### 2. The Pythonic Way: Using `@` Syntax\nPython provides a clean syntax for doing the exact same thing using the `@` symbol:\n\n```python\n@my_decorator\ndef say_hello():\n    print("Hello!")\n\n\n# Calling it normally:\nsay_hello()\n```\nWriting `@my_decorator` above `def say_hello()` is just a shortcut for `say_hello = my_decorator(say_hello)`.\n\n---\n\n### Handling Functions with Arguments\n\nWhat if your original function takes arguments? (e.g., `greet(name)`). \n\nTo make a decorator work with *any* function, use `*args` and `**kwargs` in the inner wrapper function:\n\n```python\ndef log_decorator(func):\n    def wrapper(*args, **kwargs):\n        print(f"Running function '{func.__name__}'...")\n        result = func(*args, **kwargs)  # Pass arguments to the original function\n        print("Done!")\n        return result  # Make sure to return the original function's output\n\n    return wrapper\n\n\n@log_decorator\ndef add_numbers(a, b):\n    return a + b\n\n\nsum_result = add_numbers(5, 10)\nprint(f"Result: {sum_result}")\n```\n\n**Output:**\n```text\nRunning function 'add_numbers'...\nDone!\nResult: 15\n```\n\n---\n\n### Important Best Practice: `@functools.wraps`\n\nWhen you decorate a function, its name and identity get replaced by the wrapper function. This can mess up debugging and documentation.\n\nTo fix this, Python provides `functools.wraps`:\n\n```python\nimport functools\n\n\ndef my_decorator(func):\n    @functools.wraps(func)  # <--- Preserves the original function's name and docs\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n\n    return wrapper\n```\n\n---\n\n### Real-World Example: Measuring Code Execution Time\n\nHere is a practical timing decorator you can use in real Python projects to measure performance:\n\n```python\nimport functools\nimport time\n\n\ndef timer(func):\n    """Prints the execution time of a function."""\n\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        start_time = time.perf_counter()  # Start timer\n\n        result = func(*args, **kwargs)  # Run function\n\n        end_time = time.perf_counter()  # Stop timer\n        execution_time = end_time - start_time\n        print(\n            f"Function '{func.__name__}' took {execution_time:.4f} seconds to run."\n        )\n\n        return result\n\n    return wrapper\n\n\n# --- Usage ---\n\n\n@timer\ndef heavy_computation():\n    # Simulate a slow task\n    time.sleep(1.5)\n\n\nheavy_computation()\n```\n\n**Output:**\n```text\nFunction 'heavy_computation' took 1.5012 seconds to run.\n```\n\n---\n\n### Common Use Cases for Decorators\n\nIn real software development, decorators are widely used for:\n1. **Logging:** Tracking what functions get called and when.\n2. **Authentication/Authorization:** Checking if a user is logged in before giving access to a webpage (very common in Flask and Django).\n3. **Caching:** Storing the results of expensive function calls to save computation time (`@functools.lru_cache`).\n4. **Input Validation:** Checking if inputs to a function meet certain criteria before processing.\n\n### Summary\n* A decorator is a function that takes a function and returns a new function.\n* The `@decorator_name` syntax is syntactic sugar to make your code cleaner.\n* Always use `*args, **kwargs` in the wrapper so it works with any parameters.\n* Use `@functools.wraps(func)` to preserve your original function's metadata.	2026-08-11 10:03:06.364707+00	4
15	ASSISTANT	In Python, a **decorator** is a design pattern used to extend or modify the behavior of a function or class without directly changing its original source code. \n\nThink of a decorator like a **phone case**: your phone still works the exact same way, but the case adds extra features (like water protection or a kickstand) on top of it.\n\n---\n\n### Prerequisites: Why do Decorators Work?\n\nTo understand decorators, you first need to know that in Python, **functions are first-class citizens**. This means functions can be:\n1. Assigned to variables.\n2. Passed as arguments to other functions.\n3. Returned from other functions.\n\n```python\ndef shout(text):\n    return text.upper()\n\n# Assigning a function to a variable\nsay_loud = shout \nprint(say_loud("hello")) # Output: HELLO\n```\n\n---\n\n### Step 1: Building a Decorator from Scratch\n\nA decorator is simply a function that takes another function as an argument, defines an inner "wrapper" function, and returns that inner function.\n\nHere is a decorator that prints messages before and after executing a function:\n\n```python\ndef my_decorator(func):\n    def wrapper():\n        print("1. Something is happening BEFORE the function runs.")\n        func()  # Execute the original function\n        print("2. Something is happening AFTER the function runs.")\n        \n    return wrapper  # Return the modified function\n\ndef say_hello():\n    print("Hello!")\n\n# Manually wrapping the function\nsay_hello = my_decorator(say_hello)\n\n# Call the wrapped function\nsay_hello()\n```\n\n**Output:**\n```text\n1. Something is happening BEFORE the function runs.\nHello!\n2. Something is happening AFTER the function runs.\n```\n\n---\n\n### Step 2: The `@` Syntactic Sugar\n\nPython makes this cleaner using the `@` symbol. Instead of writing `say_hello = my_decorator(say_hello)`, you simply place `@my_decorator` above your function definition.\n\n```python\n@my_decorator\ndef say_hello():\n    print("Hello!")\n\nsay_hello()\n```\n*This produces the exact same output as Step 1.*\n\n---\n\n### Step 3: Handling Arguments in Decorated Functions\n\nWhat if the function you want to decorate accepts arguments? For example, `greet(name)`?\n\nTo make a decorator flexible enough to work on *any* function, you pass `*args` and `**kwargs` into the `wrapper` function:\n\n```python\ndef my_decorator(func):\n    def wrapper(*args, **kwargs):\n        print("Executing function...")\n        result = func(*args, **kwargs) # Pass arguments through\n        return result\n    return wrapper\n\n@my_decorator\ndef greet(name, age):\n    print(f"Hello {name}, you are {age} years old.")\n\ngreet("Alice", 30)\n```\n\n---\n\n### Step 4: Best Practice – Using `functools.wraps`\n\nWhen you decorate a function, its identity changes. It technically becomes the inner `wrapper` function, which means it loses its original name and docstring.\n\nTo fix this, use `@wraps` from Python's built-in `functools` module:\n\n```python\nfrom functools import wraps\n\ndef my_decorator(func):\n    @wraps(func)  # Preserves original name and docstring\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper\n\n@my_decorator\ndef add(a, b):\n    """Adds two numbers."""\n    return a + b\n\nprint(add.__name__) # Output: add (Without @wraps, it would output 'wrapper')\n```\n\n---\n\n### Real-World Example: Measuring Execution Time\n\nOne of the most common uses for decorators is measuring how long a function takes to execute (useful for performance debugging).\n\n```python\nimport time\nfrom functools import wraps\n\ndef timer_decorator(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start_time = time.time()\n        \n        result = func(*args, **kwargs) # Run original function\n        \n        end_time = time.time()\n        execution_time = end_time - start_time\n        print(f"Function '{func.__name__}' took {execution_time:.4f} seconds.")\n        \n        return result\n    return wrapper\n\n@timer_decorator\ndef heavy_computation():\n    # Simulate a slow process\n    time.sleep(1.5)\n    return "Done!"\n\nheavy_computation()\n# Output: Function 'heavy_computation' took 1.5012 seconds.\n```\n\n---\n\n### Common Practical Use Cases\n\n1. **Logging:** Automatically logging when a function is called and what arguments it received.\n2. **Authentication / Authorization:** Checking if a user is logged in before allowing access to a web route (commonly used in web frameworks like Flask and Django).\n3. **Caching / Memoization:** Storing the results of expensive function calls (e.g., Python's built-in `@functools.lru_cache`).\n4. **Input Validation:** Ensuring inputs match specific criteria before running the function logic.\n\n---\n\n### Summary Checklist\n\n* A decorator takes a **function as input** and **returns a new function**.\n* Use the **`@decorator_name`** syntax to apply it.\n* Use **`*args, **kwargs`** in the wrapper so it works with any parameters.\n* Always use **`from functools import wraps`** and `@wraps(func)` inside your decorator to preserve the original function's identity.	2026-08-11 10:03:07.893698+00	5
21	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-11 10:54:40.46245+00	8
22	ASSISTANT	The fundamental difference between a Python **list** and a **tuple** comes down to one main concept: **mutability** (whether or not the data can be changed after it is created).\n\n---\n\n### The Main Differences\n\n| Feature | List | Tuple |\n| :--- | :--- | :--- |\n| **Mutability** | **Mutable** (Can be changed, added to, or removed from) | **Immutable** (Cannot be changed once created) |\n| **Syntax** | Uses square brackets: `[1, 2, 3]` | Uses parentheses: `(1, 2, 3)` |\n| **Performance** | Slightly slower, uses more memory | Slightly faster, uses less memory |\n| **Built-in Methods**| Has many methods (`append()`, `remove()`, `sort()`, etc.) | Has very few methods (`count()`, `index()`) |\n\n---\n\n### When to use a LIST (with Example)\n\nUse a **list** when you have a collection of items that **will change** over time—meaning you need to add, remove, or modify elements.\n\n**Example: A Shopping Cart**\nAs a user browses an online store, they add and remove items from their cart. \n\n```python\n# Create a list of items in a shopping cart\ncart = ["apples", "milk", "bread"]\n\n# Add an item to the list\ncart.append("eggs")\n\n# Remove an item from the list\ncart.remove("milk")\n\nprint(cart)  # Output: ['apples', 'bread', 'eggs']\n```\n\n---\n\n### When to use a TUPLE (with Example)\n\nUse a **tuple** when you have a collection of items that **should never change**. Tuples act as a safety net to prevent accidental modifications to fixed data (like coordinates, date of birth, or database records).\n\n**Example: GPS Coordinates**\nA specific location on Earth is defined by a pair of numbers (latitude and longitude) that should always stay together and never change.\n\n```python\n# Create a tuple for the location of the Eiffel Tower (Latitude, Longitude)\neiffel_tower_location = (48.8584, 2.2945)\n\n# If you try to change one of the values, Python throws an error:\n# eiffel_tower_location[0] = 50.0  \n# TypeError: 'tuple' object does not support item assignment\n```\n\n---\n\n### Rule of Thumb\n* If your data is a **dynamic collection** that will grow, shrink, or be reordered $\\rightarrow$ **Use a List**.\n* If your data is a **fixed structure** or constant values that belong together $\\rightarrow$ **Use a Tuple**.	2026-08-11 10:54:48.969373+00	8
23	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-11 11:01:33.713153+00	9
24	ASSISTANT	The main difference between a Python **list** and a **tuple** comes down to one word: **mutability** (whether or not the data can be changed after it is created).\n\n---\n\n### Key Differences\n\n| Feature | **List** | **Tuple** |\n| :--- | :--- | :--- |\n| **Mutability** | **Mutable** (Can be changed: add, remove, or modify items). | **Immutable** (Cannot be changed once created). |\n| **Syntax** | Uses square brackets: `[1, 2, 3]` | Uses parentheses: `(1, 2, 3)` |\n| **Performance** | Slightly slower and uses more memory. | Faster and uses less memory. |\n| **Methods** | Has many built-in methods (e.g., `.append()`, `.pop()`, `.sort()`). | Has few methods (only `.count()` and `.index()`). |\n\n---\n\n### When to use a LIST (With Example)\n\nUse a **list** when you have a collection of items that **will change** over time, or when you don't know how many items you will end up with.\n\n**Example: A Shopping Cart**\nYou constantly add items to a shopping cart or remove them before checking out, so a list is the perfect tool.\n\n```python\n# Create a list\nshopping_cart = ["apples", "milk", "bread"]\n\n# Add an item (Lists allow changing data)\nshopping_cart.append("eggs")\n\n# Remove an item\nshopping_cart.remove("milk")\n\nprint(shopping_cart)  # Output: ['apples', 'bread', 'eggs']\n```\n\n---\n\n### When to use a TUPLE (With Example)\n\nUse a **tuple** when your data **should not change**. This acts as a safeguard against accidental modifications and lets anyone reading your code know, *"This data is fixed."*\n\n**Example: GPS Coordinates**\nThe latitude and longitude of a specific landmark will never change. Bundling them in a tuple ensures they remain fixed together as a single record.\n\n```python\n# Create a tuple for GPS coordinates (Latitude, Longitude)\nlocation_paris = (48.8566, 2.3522)\n\n# If you try to change a value, Python will throw an Error:\n# location_paris[0] = 50.0  <-- TypeError: 'tuple' object does not support item assignment\n\n# Accessing values works just like a list:\nprint(f"Latitude: {location_paris[0]}")  # Output: Latitude: 48.8566\n```\n\n---\n\n### Summary Rule of Thumb\n* Use a **List** for dynamic data (e.g., a list of active users, high scores, or to-do tasks).\n* Use a **Tuple** for static data (e.g., RGB color codes `(255, 255, 255)`, dimensions `(width, height)`, or database records).	2026-08-11 11:01:41.9641+00	9
25	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-11 11:16:04.62485+00	10
26	ASSISTANT	The main difference between a Python **list** and a **tuple** comes down to one key concept: **mutability** (whether or not the data can be changed after it is created).\n\n---\n\n### The Core Differences\n\n| Feature | List | Tuple |\n| :--- | :--- | :--- |\n| **Mutability** | **Mutable** (Can be changed) | **Immutable** (Cannot be changed) |\n| **Syntax** | Square brackets: `[1, 2, 3]` | Parentheses: `(1, 2, 3)` |\n| **Performance** | Slightly slower, uses more memory | Faster, uses less memory |\n| **Intent** | Designed for collections that will change | Designed for fixed, constant data |\n\n---\n\n### 1. When to use a LIST (With Example)\n\nUse a **list** when you have a collection of items that you expect to **add to, remove from, or modify** while your program is running.\n\n**Example: A Shopping Cart**\nItems are constantly being added or removed as a user shops, so a list is the perfect choice.\n\n```python\n# Create a list of items in a shopping cart\ncart = ["apples", "bread", "milk"]\n\n# Add an item (Lists allow this)\ncart.append("eggs")\n\n# Remove an item\ncart.remove("bread")\n\nprint(cart)  # Output: ['apples', 'milk', 'eggs']\n```\n\n---\n\n### 2. When to use a TUPLE (With Example)\n\nUse a **tuple** when your data **should never change**. This acts as a safeguard to prevent accidental modifications to important settings or fixed values.\n\n**Example: GPS Coordinates**\nA city's latitude and longitude are fixed. Changing one of the numbers would point to a completely different location on Earth, so it should be protected from accidental edits.\n\n```python\n# Create a tuple for GPS coordinates (Latitude, Longitude)\nsan_francisco_coords = (37.7749, -122.4194)\n\n# If you try to change one of the values:\nsan_francisco_coords[0] = 40.0  # ❌ Python throws a TypeError!\n```\n\n---\n\n### Summary Rule of Thumb\n\n* Use a **List** `[]` when you are dealing with a flexible collection of similar items (e.g., a list of high scores, tasks to do, or user comments).\n* Use a **Tuple** `()` when you are grouping a fixed set of values together that belong together as a structure (e.g., RGB color codes `(255, 0, 0)`, `(x, y)` screen coordinates, or a database record like `("John", "Doe", 1990)`).	2026-08-11 11:16:12.782077+00	10
27	USER	"Explain the difference between a Python list and a tuple, and give me a simple example of when I should use each one."	2026-08-11 11:29:07.514228+00	11
28	ASSISTANT	The main difference between a Python **list** and a **tuple** comes down to one key concept: **mutability** (whether or not the data can be changed after it is created).\n\n---\n\n### The Core Differences\n\n| Feature | List | Tuple |\n| :--- | :--- | :--- |\n| **Mutability** | **Mutable** (Can be changed) | **Immutable** (Cannot be changed) |\n| **Syntax** | Square brackets: `[1, 2, 3]` | Parentheses: `(1, 2, 3)` |\n| **Performance** | Slightly slower, uses more memory | Slightly faster, uses less memory |\n| **Common Use** | For collections of data that will change | For data that should remain constant |\n\n---\n\n### 1. When to use a List (Example)\n\nUse a **list** when you have a collection of items that **will change** over time—such as adding, removing, or modifying elements.\n\n**Example: A Shopping Cart**\nAs a user browses a store, items are constantly added or removed from their cart.\n\n```python\n# A list of items in a shopping cart\ncart = ["apples", "milk", "bread"]\n\n# You CAN add items to a list\ncart.append("eggs")\n\n# You CAN remove items from a list\ncart.remove("milk")\n\nprint(cart)  # Output: ['apples', 'bread', 'eggs']\n```\n\n---\n\n### 2. When to use a Tuple (Example)\n\nUse a **tuple** when your data is a fixed group of values that **should never change** while the program is running. This acts as a safety feature to prevent accidental edits.\n\n**Example: GPS Coordinates**\nA specific location's latitude and longitude are fixed. Changing one number would point to a completely different place on Earth.\n\n```python\n# A tuple representing (Latitude, Longitude) for New York City\nnyc_coordinates = (40.7128, -74.0060)\n\n# If you try to change a tuple, Python throws an error:\nnyc_coordinates[0] = 41.0000  # ❌ TypeError: 'tuple' object does not support item assignment\n```\n\n---\n\n### Summary rule of thumb:\n* Need to **add, remove, or sort** items? **Use a List.**\n* Data is **fixed, read-only, or structural** (like RGB colors, coordinates, or database records)? **Use a Tuple.**	2026-08-11 11:29:15.420184+00	11
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add profile	7	add_profile
26	Can change profile	7	change_profile
27	Can delete profile	7	delete_profile
28	Can view profile	7	view_profile
29	Can add activity	8	add_activity
30	Can change activity	8	change_activity
31	Can delete activity	8	delete_activity
32	Can view activity	8	view_activity
33	Can add task	9	add_task
34	Can change task	9	change_task
35	Can delete task	9	delete_task
36	Can view task	9	view_task
37	Can add tag	10	add_tag
38	Can change tag	10	change_tag
39	Can delete tag	10	delete_tag
40	Can view tag	10	view_tag
41	Can add note	11	add_note
42	Can change note	11	change_note
43	Can delete note	11	delete_note
44	Can view note	11	view_note
45	Can add category	12	add_category
46	Can change category	12	change_category
47	Can delete category	12	delete_category
48	Can view category	12	view_category
49	Can add resource	13	add_resource
50	Can change resource	13	change_resource
51	Can delete resource	13	delete_resource
52	Can view resource	13	view_resource
53	Can add resource type	14	add_resourcetype
54	Can change resource type	14	change_resourcetype
55	Can delete resource type	14	delete_resourcetype
56	Can view resource type	14	view_resourcetype
57	Can add ai conversation	15	add_aiconversation
58	Can change ai conversation	15	change_aiconversation
59	Can delete ai conversation	15	delete_aiconversation
60	Can view ai conversation	15	view_aiconversation
61	Can add ai message	16	add_aimessage
62	Can change ai message	16	change_aimessage
63	Can delete ai message	16	delete_aimessage
64	Can view ai message	16	view_aimessage
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$fs72yVvFKFhqg7Mwn5yuhq$RLrCWSC1ew/nELSDAtKhh0+HNgkTfkPeUpW/lQFMJC8=	\N	f	magdy			magdy@gmail.com	f	f	2026-08-11 10:29:30.578687+00
3	pbkdf2_sha256$1000000$20Pbm60ZU83VTu3UGVJRq8$WMEFV8q/En1awPHaHw0nFp+15TVpcuStNdOIbbMGqkI=	2026-08-11 10:35:21.111973+00	t	magdy1			magdy1@gmail.com	t	t	2026-08-11 10:34:21.412381+00
1	pbkdf2_sha256$1000000$3RMBHiq14pfWnilE51xByK$VLaMKDdNebNdziPz1jsupbK/TuWVwf3r5SskcFolkrI=	2026-08-12 13:39:36.997855+00	t	rawan	rawan	magdy	a12aaascii@gmail.com	t	t	2026-08-10 15:34:28.816454+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: dashboard_activity; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.dashboard_activity (id, action, created_at, user_id) FROM stdin;
1	Created task: task1	2026-08-10 16:09:06.725973+00	1
2	Asked AI: "Explain the difference between a Python	2026-08-10 17:47:07.073761+00	1
3	Asked AI: "Explain the difference between a Python	2026-08-10 17:47:54.832068+00	1
4	Asked AI: Explain Python decorators	2026-08-10 17:49:54.548431+00	1
5	Created task: python1	2026-08-10 17:56:35.188292+00	1
6	Updated task: task1	2026-08-10 17:56:42.691958+00	1
7	Created task: task3	2026-08-11 09:29:24.85431+00	1
8	Created note: note1	2026-08-11 09:29:59.582741+00	1
9	Asked AI: Explain Python decorators	2026-08-11 09:36:46.856542+00	1
10	Created note: note2	2026-08-11 09:56:20.079381+00	1
11	Created note: note2	2026-08-11 09:56:25.448619+00	1
12	Deleted note: note2	2026-08-11 09:56:37.047205+00	1
13	Asked AI: "Explain the difference between a Python	2026-08-11 09:57:53.423469+00	1
14	Asked AI: Explain Python decorators	2026-08-11 10:03:06.369246+00	1
15	Asked AI: Explain Python decorators	2026-08-11 10:03:07.897562+00	1
16	Asked AI: Explain Python decorators	2026-08-11 10:03:08.721121+00	1
17	Asked AI: t3ref meen amr diab??	2026-08-11 10:04:11.91449+00	1
18	Added resource: resource1	2026-08-11 10:13:48.817419+00	1
19	Created note: note3	2026-08-11 10:14:56.830428+00	1
20	Created note: note2	2026-08-11 10:36:02.503739+00	3
21	Created note: note4	2026-08-11 10:45:00.39816+00	1
22	Deleted note: note2	2026-08-11 10:52:00.487443+00	1
23	Created note: note2	2026-08-11 10:52:24.572353+00	1
24	Created note: note5	2026-08-11 10:52:57.468965+00	1
25	Asked AI: t3raf meen abdelrahman aziz??	2026-08-11 10:53:56.133474+00	1
26	Asked AI: "Explain the difference between a Python	2026-08-11 10:54:48.972513+00	1
27	Asked AI: "Explain the difference between a Python	2026-08-11 11:01:41.96725+00	1
28	Created task: task3	2026-08-11 11:14:41.409465+00	1
29	Created note: note6	2026-08-11 11:15:17.483273+00	1
30	Added resource: resource2	2026-08-11 11:15:55.87867+00	1
31	Asked AI: "Explain the difference between a Python	2026-08-11 11:16:12.784552+00	1
32	Deleted resource: resource2	2026-08-11 11:18:53.611458+00	1
33	Created task: task5	2026-08-11 11:28:29.251084+00	1
34	Created note: note7	2026-08-11 11:28:45.859953+00	1
35	Asked AI: "Explain the difference between a Python	2026-08-11 11:29:15.424249+00	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-11 10:12:58.194419+00	1	python	1	[{"added": {}}]	14	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	profile
8	dashboard	activity
9	planner	task
10	notes	tag
11	notes	note
12	notes	category
13	resources	resource
14	resources	resourcetype
15	ai_assistant	aiconversation
16	ai_assistant	aimessage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-10 14:55:06.456531+00
2	auth	0001_initial	2026-08-10 14:55:06.500511+00
3	admin	0001_initial	2026-08-10 14:55:06.5113+00
4	admin	0002_logentry_remove_auto_add	2026-08-10 14:55:06.514413+00
5	admin	0003_logentry_add_action_flag_choices	2026-08-10 14:55:06.516582+00
6	contenttypes	0002_remove_content_type_name	2026-08-10 14:55:06.521697+00
7	auth	0002_alter_permission_name_max_length	2026-08-10 14:55:06.527408+00
8	auth	0003_alter_user_email_max_length	2026-08-10 14:55:06.529922+00
9	auth	0004_alter_user_username_opts	2026-08-10 14:55:06.531993+00
10	auth	0005_alter_user_last_login_null	2026-08-10 14:55:06.534381+00
11	auth	0006_require_contenttypes_0002	2026-08-10 14:55:06.534862+00
12	auth	0007_alter_validators_add_error_messages	2026-08-10 14:55:06.537169+00
13	auth	0008_alter_user_username_max_length	2026-08-10 14:55:06.541274+00
14	auth	0009_alter_user_last_name_max_length	2026-08-10 14:55:06.544002+00
15	auth	0010_alter_group_name_max_length	2026-08-10 14:55:06.547344+00
16	auth	0011_update_proxy_permissions	2026-08-10 14:55:06.549281+00
17	auth	0012_alter_user_first_name_max_length	2026-08-10 14:55:06.552296+00
18	sessions	0001_initial	2026-08-10 14:55:06.558167+00
19	accounts	0001_initial	2026-08-10 15:16:47.893501+00
20	ai_assistant	0001_initial	2026-08-10 15:16:47.910659+00
21	dashboard	0001_initial	2026-08-10 15:16:47.918392+00
22	notes	0001_initial	2026-08-10 15:16:47.951936+00
23	planner	0001_initial	2026-08-10 15:16:47.96198+00
24	resources	0001_initial	2026-08-10 15:16:47.975463+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ixzxo8ba5ie2t3syfs3mjkby6qyeijm4	.eJxVjrsOwjAUQ_8lM1RpmtskjOx8Q5T7gPJQg5pWDIh_J5W6dLPsY8tfFd-plE-eOE5SZI5zfsqoTorZheVx7AU0gHhwNnjTEWIVfSCDGjU7VAcV0zIPcSkyxTvXZrv3MFFdXAN-pPGWG8rjPN2xWZFmS0tzySyv88buBoZUhto2JFexNrTgUFvy0PvA1oROJ6wXnWMkAO08295zfZiILYEH9NJpMer3B3cSS_U:1wu9BA:QzzXO7otfnXfhVgX_r0XC59RSOub1V8Moh7bn67aUv0	2026-08-26 13:39:36.99889+00
\.


--
-- Data for Name: notes_category; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.notes_category (id, name, user_id) FROM stdin;
1	python	1
2	css	1
3	category2	3
4	category3	1
5	category4	1
\.


--
-- Data for Name: notes_note; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.notes_note (id, title, content, created_at, updated_at, category_id, user_id) FROM stdin;
4	note3	css	2026-08-11 10:14:56.824979+00	2026-08-11 10:14:56.824999+00	2	1
5	note2	css	2026-08-11 10:36:02.500279+00	2026-08-11 10:36:02.500291+00	3	3
6	note4	css	2026-08-11 10:45:00.391202+00	2026-08-11 10:45:00.391225+00	2	1
7	note2	python	2026-08-11 10:52:24.567204+00	2026-08-11 10:52:24.567234+00	1	1
1	note1	python	2026-08-11 09:29:59.573367+00	2026-08-11 10:52:33.955276+00	1	1
8	note5	css	2026-08-11 10:52:57.464358+00	2026-08-11 10:52:57.464379+00	2	1
9	note6	python	2026-08-11 11:15:17.478409+00	2026-08-11 11:15:17.478458+00	1	1
10	note7	python1	2026-08-11 11:28:45.854042+00	2026-08-11 11:28:45.854062+00	1	1
\.


--
-- Data for Name: notes_note_tags; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.notes_note_tags (id, note_id, tag_id) FROM stdin;
\.


--
-- Data for Name: notes_tag; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.notes_tag (id, name, user_id) FROM stdin;
\.


--
-- Data for Name: planner_task; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.planner_task (id, title, description, due_date, priority, status, created_at, updated_at, user_id) FROM stdin;
2	python1	python	2026-08-10	MEDIUM	COMPLETED	2026-08-10 17:56:35.186041+00	2026-08-10 17:56:35.186051+00	1
1	task1	python	2026-08-10	MEDIUM	COMPLETED	2026-08-10 16:09:06.72205+00	2026-08-10 17:56:42.688647+00	1
3	task3	css	2026-08-11	HIGH	PENDING	2026-08-11 09:29:24.847871+00	2026-08-11 09:29:24.847891+00	1
4	task3	python	2026-08-11	LOW	COMPLETED	2026-08-11 11:14:41.406402+00	2026-08-11 11:14:41.40642+00	1
5	task5	python	2026-08-11	HIGH	PENDING	2026-08-11 11:28:29.248262+00	2026-08-11 11:28:29.248284+00	1
\.


--
-- Data for Name: resources_resource; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.resources_resource (id, title, description, link, created_at, user_id, resource_type_id) FROM stdin;
1	resource1	python	https://www.learnpython.org/	2026-08-11 10:13:48.812817+00	1	1
\.


--
-- Data for Name: resources_resourcetype; Type: TABLE DATA; Schema: public; Owner: aistudyhub_user
--

COPY public.resources_resourcetype (id, name) FROM stdin;
1	python
\.


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 3, true);


--
-- Name: ai_assistant_aiconversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.ai_assistant_aiconversation_id_seq', 11, true);


--
-- Name: ai_assistant_aimessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.ai_assistant_aimessage_id_seq', 28, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: dashboard_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.dashboard_activity_id_seq', 35, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: notes_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.notes_category_id_seq', 5, true);


--
-- Name: notes_note_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.notes_note_id_seq', 10, true);


--
-- Name: notes_note_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.notes_note_tags_id_seq', 1, false);


--
-- Name: notes_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.notes_tag_id_seq', 1, false);


--
-- Name: planner_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.planner_task_id_seq', 5, true);


--
-- Name: resources_resource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.resources_resource_id_seq', 2, true);


--
-- Name: resources_resourcetype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aistudyhub_user
--

SELECT pg_catalog.setval('public.resources_resourcetype_id_seq', 1, true);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: ai_assistant_aiconversation ai_assistant_aiconversation_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.ai_assistant_aiconversation
    ADD CONSTRAINT ai_assistant_aiconversation_pkey PRIMARY KEY (id);


--
-- Name: ai_assistant_aimessage ai_assistant_aimessage_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.ai_assistant_aimessage
    ADD CONSTRAINT ai_assistant_aimessage_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: dashboard_activity dashboard_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.dashboard_activity
    ADD CONSTRAINT dashboard_activity_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: notes_category notes_category_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_category
    ADD CONSTRAINT notes_category_pkey PRIMARY KEY (id);


--
-- Name: notes_note notes_note_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_pkey PRIMARY KEY (id);


--
-- Name: notes_note_tags notes_note_tags_note_id_tag_id_e85f93da_uniq; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_note_id_tag_id_e85f93da_uniq UNIQUE (note_id, tag_id);


--
-- Name: notes_note_tags notes_note_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_pkey PRIMARY KEY (id);


--
-- Name: notes_tag notes_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_tag
    ADD CONSTRAINT notes_tag_pkey PRIMARY KEY (id);


--
-- Name: planner_task planner_task_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.planner_task
    ADD CONSTRAINT planner_task_pkey PRIMARY KEY (id);


--
-- Name: resources_resource resources_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_pkey PRIMARY KEY (id);


--
-- Name: resources_resourcetype resources_resourcetype_name_key; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.resources_resourcetype
    ADD CONSTRAINT resources_resourcetype_name_key UNIQUE (name);


--
-- Name: resources_resourcetype resources_resourcetype_pkey; Type: CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.resources_resourcetype
    ADD CONSTRAINT resources_resourcetype_pkey PRIMARY KEY (id);


--
-- Name: ai_assistant_aiconversation_user_id_cc575851; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX ai_assistant_aiconversation_user_id_cc575851 ON public.ai_assistant_aiconversation USING btree (user_id);


--
-- Name: ai_assistant_aimessage_conversation_id_1e9c58b6; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX ai_assistant_aimessage_conversation_id_1e9c58b6 ON public.ai_assistant_aimessage USING btree (conversation_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: dashboard_activity_user_id_75cecb87; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX dashboard_activity_user_id_75cecb87 ON public.dashboard_activity USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: notes_category_user_id_b17705fe; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_category_user_id_b17705fe ON public.notes_category USING btree (user_id);


--
-- Name: notes_note_category_id_dfff76db; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_note_category_id_dfff76db ON public.notes_note USING btree (category_id);


--
-- Name: notes_note_tags_note_id_3c701a99; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_note_tags_note_id_3c701a99 ON public.notes_note_tags USING btree (note_id);


--
-- Name: notes_note_tags_tag_id_e3814610; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_note_tags_tag_id_e3814610 ON public.notes_note_tags USING btree (tag_id);


--
-- Name: notes_note_user_id_be6c80b4; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_note_user_id_be6c80b4 ON public.notes_note USING btree (user_id);


--
-- Name: notes_tag_user_id_bddac101; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX notes_tag_user_id_bddac101 ON public.notes_tag USING btree (user_id);


--
-- Name: planner_task_user_id_9361dd5c; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX planner_task_user_id_9361dd5c ON public.planner_task USING btree (user_id);


--
-- Name: resources_resource_resource_type_id_84cc460b; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX resources_resource_resource_type_id_84cc460b ON public.resources_resource USING btree (resource_type_id);


--
-- Name: resources_resource_user_id_fde5fc52; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX resources_resource_user_id_fde5fc52 ON public.resources_resource USING btree (user_id);


--
-- Name: resources_resourcetype_name_da790f9e_like; Type: INDEX; Schema: public; Owner: aistudyhub_user
--

CREATE INDEX resources_resourcetype_name_da790f9e_like ON public.resources_resourcetype USING btree (name varchar_pattern_ops);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_assistant_aiconversation ai_assistant_aiconversation_user_id_cc575851_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.ai_assistant_aiconversation
    ADD CONSTRAINT ai_assistant_aiconversation_user_id_cc575851_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_assistant_aimessage ai_assistant_aimessa_conversation_id_1e9c58b6_fk_ai_assist; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.ai_assistant_aimessage
    ADD CONSTRAINT ai_assistant_aimessa_conversation_id_1e9c58b6_fk_ai_assist FOREIGN KEY (conversation_id) REFERENCES public.ai_assistant_aiconversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dashboard_activity dashboard_activity_user_id_75cecb87_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.dashboard_activity
    ADD CONSTRAINT dashboard_activity_user_id_75cecb87_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_category notes_category_user_id_b17705fe_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_category
    ADD CONSTRAINT notes_category_user_id_b17705fe_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_note notes_note_category_id_dfff76db_fk_notes_category_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_category_id_dfff76db_fk_notes_category_id FOREIGN KEY (category_id) REFERENCES public.notes_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_note_tags notes_note_tags_note_id_3c701a99_fk_notes_note_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_note_id_3c701a99_fk_notes_note_id FOREIGN KEY (note_id) REFERENCES public.notes_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_note_tags notes_note_tags_tag_id_e3814610_fk_notes_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note_tags
    ADD CONSTRAINT notes_note_tags_tag_id_e3814610_fk_notes_tag_id FOREIGN KEY (tag_id) REFERENCES public.notes_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_note notes_note_user_id_be6c80b4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_note
    ADD CONSTRAINT notes_note_user_id_be6c80b4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes_tag notes_tag_user_id_bddac101_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.notes_tag
    ADD CONSTRAINT notes_tag_user_id_bddac101_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planner_task planner_task_user_id_9361dd5c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.planner_task
    ADD CONSTRAINT planner_task_user_id_9361dd5c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resource resources_resource_resource_type_id_84cc460b_fk_resources; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_resource_type_id_84cc460b_fk_resources FOREIGN KEY (resource_type_id) REFERENCES public.resources_resourcetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources_resource resources_resource_user_id_fde5fc52_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aistudyhub_user
--

ALTER TABLE ONLY public.resources_resource
    ADD CONSTRAINT resources_resource_user_id_fde5fc52_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO aistudyhub_user;


--
-- PostgreSQL database dump complete
--

\unrestrict VrBcl8f5fuavBOMJfHOkRRBiL90M2GhbT873q7jprFVIMs1GHuCczYIBPob4yrK

